"""Initial schema with updated monitoring_sites

Revision ID: 55d4c7aa85ce
Revises: 
Create Date: 2026-03-07 02:46:11.468336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d4c7aa85ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user'], unique=False)
    op.create_table('monitoring_sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitoring_sites_compliance_status', 'monitoring_sites', ['compliance_status'], unique=False)
    op.create_index('ix_monitoring_sites_is_active', 'monitoring_sites', ['is_active'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('validation_result_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_violations_detected_at', 'violations', ['detected_at'], unique=False)
    op.create_index('ix_violations_severity', 'violations', ['severity'], unique=False)
    op.create_index('ix_violations_type', 'violations', ['violation_type'], unique=False)
    op.create_index('ix_violations_validation_result_id', 'violations', ['validation_result_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('slack_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_violation_id', 'alerts', ['violation_id'], unique=False)
    op.create_table('contract_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subscription_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['monitoring_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_conditions_is_current', 'contract_conditions', ['is_current'], unique=False)
    op.create_index('ix_contract_conditions_site_id', 'contract_conditions', ['site_id'], unique=False)
    op.create_index('ix_contract_conditions_site_version', 'contract_conditions', ['site_id', 'version'], unique=False)
    op.create_table('crawl_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['monitoring_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawl_results_crawled_at', 'crawl_results', ['crawled_at'], unique=False)
    op.create_index('ix_crawl_results_site_crawled', 'crawl_results', ['site_id', 'crawled_at'], unique=False)
    op.create_index('ix_crawl_results_site_id', 'crawl_results', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crawl_results_site_id', table_name='crawl_results')
    op.drop_index('ix_crawl_results_site_crawled', table_name='crawl_results')
    op.drop_index('ix_crawl_results_crawled_at', table_name='crawl_results')
    op.drop_table('crawl_results')
    op.drop_index('ix_contract_conditions_site_version', table_name='contract_conditions')
    op.drop_index('ix_contract_conditions_site_id', table_name='contract_conditions')
    op.drop_index('ix_contract_conditions_is_current', table_name='contract_conditions')
    op.drop_table('contract_conditions')
    op.drop_index('ix_alerts_violation_id', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_violations_validation_result_id', table_name='violations')
    op.drop_index('ix_violations_type', table_name='violations')
    op.drop_index('ix_violations_severity', table_name='violations')
    op.drop_index('ix_violations_detected_at', table_name='violations')
    op.drop_table('violations')
    op.drop_index('ix_monitoring_sites_is_active', table_name='monitoring_sites')
    op.drop_index('ix_monitoring_sites_compliance_status', table_name='monitoring_sites')
    op.drop_table('monitoring_sites')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
