"""add_categories_field_schemas_extracted_data_tables

Revision ID: c7f1f5cab04d
Revises: 0340f3c9d609
Create Date: 2026-03-10 23:59:22.686139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f1f5cab04d'
down_revision: Union[str, None] = '0340f3c9d609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('field_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'field_name', name='uq_field_schema_category_field')
    )
    op.create_index('ix_field_schemas_category_id', 'field_schemas', ['category_id'], unique=False)
    op.create_table('extracted_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screenshot_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['monitoring_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_data_screenshot_id', 'extracted_data', ['screenshot_id'], unique=False)
    op.create_index('ix_extracted_data_site_id', 'extracted_data', ['site_id'], unique=False)
    op.add_column('alerts', sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('alerts', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_alerts_site_id', 'alerts', 'monitoring_sites', ['site_id'], ['id'])
    op.add_column('contract_conditions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_contract_conditions_category_id', 'contract_conditions', 'categories', ['category_id'], ['id'])
    op.add_column('monitoring_sites', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_monitoring_sites_category_id', 'monitoring_sites', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_monitoring_sites_category_id', 'monitoring_sites', type_='foreignkey')
    op.drop_column('monitoring_sites', 'category_id')
    op.drop_constraint('fk_contract_conditions_category_id', 'contract_conditions', type_='foreignkey')
    op.drop_column('contract_conditions', 'category_id')
    op.drop_constraint('fk_alerts_site_id', 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'site_id')
    op.drop_column('alerts', 'is_resolved')
    op.drop_index('ix_extracted_data_site_id', table_name='extracted_data')
    op.drop_index('ix_extracted_data_screenshot_id', table_name='extracted_data')
    op.drop_table('extracted_data')
    op.drop_index('ix_field_schemas_category_id', table_name='field_schemas')
    op.drop_table('field_schemas')
    op.drop_table('categories')
    # ### end Alembic commands ###
