"""add_customer_and_screenshot

Revision ID: fdc38e236687
Revises: 55d4c7aa85ce
Create Date: 2026-03-07 03:44:12.143438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc38e236687'
down_revision: Union[str, None] = '55d4c7aa85ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create customers table first
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_is_active', 'customers', ['is_active'], unique=False)
    
    # Create a default customer for existing sites
    op.execute("""
        INSERT INTO customers (name, company_name, email, is_active, created_at, updated_at)
        VALUES ('デフォルト顧客', 'デフォルト会社', 'default@example.com', true, NOW(), NOW())
    """)
    
    # Add screenshot_path to crawl_results
    op.add_column('crawl_results', sa.Column('screenshot_path', sa.Text(), nullable=True))
    
    # Add customer_id column as nullable first
    op.add_column('monitoring_sites', sa.Column('customer_id', sa.Integer(), nullable=True))
    
    # Set default customer_id for existing sites
    op.execute("""
        UPDATE monitoring_sites 
        SET customer_id = (SELECT id FROM customers WHERE email = 'default@example.com' LIMIT 1)
        WHERE customer_id IS NULL
    """)
    
    # Now make customer_id NOT NULL
    op.alter_column('monitoring_sites', 'customer_id', nullable=False)
    
    # Create index and foreign key
    op.create_index('ix_monitoring_sites_customer_id', 'monitoring_sites', ['customer_id'], unique=False)
    op.create_foreign_key('fk_monitoring_sites_customer_id', 'monitoring_sites', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_monitoring_sites_customer_id', 'monitoring_sites', type_='foreignkey')
    op.drop_index('ix_monitoring_sites_customer_id', table_name='monitoring_sites')
    op.drop_column('monitoring_sites', 'customer_id')
    op.drop_column('crawl_results', 'screenshot_path')
    op.drop_index('ix_customers_is_active', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
